/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5.2.1 2003/07/02 17:36:07 hardaker Exp $
 */
/*********************************************************
* Modified  by Deltanetwork  2004.12.25 --- DNI  
* modules for dot1dbridge, base net-snmp-5.0.9
*  auto generated by  mib2c code and I  merge it to dot1dbridge
***********************************************************/
#ifndef DOT1DBRIDGE_TABLE_H
#define DOT1DBRIDGE_TABLE_H

#define CB3000_MAC_ADDRESS_LENGTH  6		/* Mac length */
#define DOT1D_MAX_PACKET_SIZE    1518		/* MTU  */
#define CB3000_Max_portnum 2				/* we only have two port */
#define CB3000_Min_portnum	1

/*
typedef struct FdbIndex_S
{
	unsigned char maclist[6];
	int portId;
}Fdbindex_t;
*/

struct Bridge_Id
{
	unsigned char prio[2];
	unsigned char addr[6];
};


typedef struct StpTable_S{
	
	int stpport;
	char portname[5];
	int stpport_priority;
	int stpport_status;
	int stpport_enabled;
	//int stpport_pathcost;
	char stp_designatedroot[8];
	int stp_designatedcost;
	char stp_designatedbridge[8];
	char stp_designatedport[2];
	int stp_forwardtransitions;
	long stpportpathcost32;
	struct StpTable_S *next;	
}StpTable_T;


typedef struct ForwardDataBase_S{
	int index;
	int portno;
	unsigned char Mac[18];
	unsigned char local[5];
	unsigned char ageingtime[16];
}ForwardDataBase_T;


typedef struct MACINDEX_S{
	unsigned char mac[6];
	int portindex;
}MACINDEX_T;

/*
 * function declarations 
 */


void            init_dot1dBridge_table(void);
void            initialize_table_dot1dStpPortTable(void);
Netsnmp_Node_Handler dot1dStpPortTable_handler;

Netsnmp_First_Data_Point dot1dStpPortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dStpPortTable_get_next_data_point;
void            initialize_table_dot1dTpFdbTable(void);
Netsnmp_Node_Handler dot1dTpFdbTable_handler;

Netsnmp_First_Data_Point dot1dTpFdbTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dTpFdbTable_get_next_data_point;
void            initialize_table_dot1dBasePortTable(void);
Netsnmp_Node_Handler dot1dBasePortTable_handler;

Netsnmp_First_Data_Point dot1dBasePortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dBasePortTable_get_next_data_point;
void            initialize_table_dot1dTpPortTable(void);
Netsnmp_Node_Handler dot1dTpPortTable_handler;

Netsnmp_First_Data_Point dot1dTpPortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dTpPortTable_get_next_data_point;
void            initialize_table_dot1dStaticTable(void);
Netsnmp_Node_Handler dot1dStaticTable_handler;

Netsnmp_First_Data_Point dot1dStaticTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dStaticTable_get_next_data_point;

/*
 * column number definitions for table dot1dStpPortTable 
 */
#define COLUMN_DOT1DSTPPORT		1
#define COLUMN_DOT1DSTPPORTPRIORITY		2
#define COLUMN_DOT1DSTPPORTSTATE		3
#define COLUMN_DOT1DSTPPORTENABLE		4
#define COLUMN_DOT1DSTPPORTPATHCOST		5
#define COLUMN_DOT1DSTPPORTDESIGNATEDROOT		6
#define COLUMN_DOT1DSTPPORTDESIGNATEDCOST		7
#define COLUMN_DOT1DSTPPORTDESIGNATEDBRIDGE		8
#define COLUMN_DOT1DSTPPORTDESIGNATEDPORT		9
#define COLUMN_DOT1DSTPPORTFORWARDTRANSITIONS		10
#define COLUMN_DOT1DSTPPORTPATHCOST32		11

/*
 * column number definitions for table dot1dTpFdbTable 
 */
#define COLUMN_DOT1DTPFDBADDRESS		1
#define COLUMN_DOT1DTPFDBPORT		2
#define COLUMN_DOT1DTPFDBSTATUS		3

/*
 * column number definitions for table dot1dBasePortTable 
 */
#define COLUMN_DOT1DBASEPORT		1
#define COLUMN_DOT1DBASEPORTIFINDEX		2
#define COLUMN_DOT1DBASEPORTCIRCUIT		3
#define COLUMN_DOT1DBASEPORTDELAYEXCEEDEDDISCARDS		4
#define COLUMN_DOT1DBASEPORTMTUEXCEEDEDDISCARDS		5

/*
 * column number definitions for table dot1dTpPortTable 
 */
#define COLUMN_DOT1DTPPORT		1
#define COLUMN_DOT1DTPPORTMAXINFO		2
#define COLUMN_DOT1DTPPORTINFRAMES		3
#define COLUMN_DOT1DTPPORTOUTFRAMES		4
#define COLUMN_DOT1DTPPORTINDISCARDS		5

/*
 * column number definitions for table dot1dStaticTable 
 */
#define COLUMN_DOT1DSTATICADDRESS		1
#define COLUMN_DOT1DSTATICRECEIVEPORT		2
#define COLUMN_DOT1DSTATICALLOWEDTOGOTO		3
#define COLUMN_DOT1DSTATICSTATUS		4

/* **************PRIVATE  INCLDUE FILE  BEGIN ---SOPHIE*******************/

#define SOPHIE_H
#define IF_NAME_LEN 60
#define BRIDGE_ALIAN_NAME_LEN	30
#define BRIDGE_STATS_LINE "%s %s %s %s"
#define BRIDGE_TITLE "bridge name"
#define TITLE_LINE_LEN	11
#define BRIDGE_PREFIX_LEN	16

#define FDB_STATS_LINE "%d %s %s %s"
#define FDB_TITLE "port no"
#define FDB_TITLE_LINE_LEN 7


/* local routines */
int addbridge(char*);
int delbridge(char *);
int showbridge(char *);
int showMacs(char * );
int stp_show(void);
//int getnextbridge(int argc,char ** argv[]);
//int getbridgeinfo(char *);
int getfdbinfo(char *);
int getstp(void);
void intif_info(void);
void MacstringtoMac(char *,char*);
int searchindexfrommac(unsigned char *);

/*
//this function used by scalar ,so it define in scalar now
char * getmacbyifname( char* bridgename,char * retmac);
*/

/************************** PRIVATE INLCUDE END *****************************/


#endif                          /* DOT1DBRIDGE_TABLE_H */
