/*
 * Note: this file originally auto-generated by mib2c using
 *: mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
*/
/*
* reserved by Deltanetwork  2004.12.25  sophie.chen DNI  
* modules for dot1dbridge 
*/

#ifndef DOT1DBRIDGE_H
#define DOT1DBRIDGE_H   /* not declaration reincldue  */

/*
 *  our function declarations 
*/
void	init_dot1dBridge(void);
void	init_dot1dBase(void);
void init_dot1dTp(void);
int	get_dot1dBaseBridgeAddress(netsnmp_mib_handler *,
		netsnmp_handler_registration *,
                netsnmp_agent_request_info *,
                netsnmp_request_info *);
int
get_dot1dBaseNumPorts(netsnmp_mib_handler *,
                      netsnmp_handler_registration *,
                      netsnmp_agent_request_info *,
                      netsnmp_request_info *);
int
get_dot1dBaseType(netsnmp_mib_handler *,
                  netsnmp_handler_registration *,
                  netsnmp_agent_request_info *,
                  netsnmp_request_info *);
int
get_dot1dTpLearnedEntryDiscards(netsnmp_mib_handler *,
                                netsnmp_handler_registration *,
                                netsnmp_agent_request_info *,
                                netsnmp_request_info *);


int
do_dot1dTpAgingTime(netsnmp_mib_handler *,
                    netsnmp_handler_registration *,
                    netsnmp_agent_request_info *,
                    netsnmp_request_info *);

void	initialize_table_dot1dStpPortTable(void);
Netsnmp_Node_Handler dot1dStpPortTable_handler;

Netsnmp_First_Data_Point dot1dStpPortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dStpPortTable_get_next_data_point;
void            initialize_table_dot1dTpFdbTable(void);
Netsnmp_Node_Handler dot1dTpFdbTable_handler;

Netsnmp_First_Data_Point dot1dTpFdbTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dTpFdbTable_get_next_data_point;
void            initialize_table_dot1dBasePortTable(void);
Netsnmp_Node_Handler dot1dBasePortTable_handler;

Netsnmp_First_Data_Point dot1dBasePortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dBasePortTable_get_next_data_point;
void            initialize_table_dot1dTpPortTable(void);
Netsnmp_Node_Handler dot1dTpPortTable_handler;

Netsnmp_First_Data_Point dot1dTpPortTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dTpPortTable_get_next_data_point;
void            initialize_table_dot1dStaticTable(void);
Netsnmp_Node_Handler dot1dStaticTable_handler;

Netsnmp_First_Data_Point dot1dStaticTable_get_first_data_point;
Netsnmp_Next_Data_Point dot1dStaticTable_get_next_data_point;
#include "dot1dBridge_columns.h"
#include "dot1dBridge_enums.h"
#endif                        
