/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "atherosAPdot11_scalar.h"


typedef unsigned int 	MYINTEGER;
typedef unsigned int 	MYEnumVal;

static void *	backupBuf;
static int		valLen;
static int 		bufLen;

static int backup(const void* val,int len)//val in
{
	if(valLen!=0)
		return -1;
	if(len>bufLen)
	{
		free(backupBuf);
		if(!(backupBuf=malloc(len)))
		{
			bufLen=0;
			return 1;
		}
		bufLen=len;
	}
	memcpy(backupBuf,val,len);
	valLen=len;
	return 0;
}

static int restore(void* val,int len)
{
	if(len!=valLen || val==NULL)
		return -1;
	memcpy(val,backupBuf,valLen);
	valLen=0;
	return 0;
}

static int clear()
{
	//if(valLen==0)
	//	return -1;
	valLen=0;
	return 0;
}

/** Initializes the atherosAPdot11_scalar module */
void
init_atherosAPdot11_scalar(void)
{
	bufLen=0;
	backupBuf=NULL;
	valLen=0;
    static oid      dot11MultiDomainCapabilityEnabled_oid[] =
        { 1, 3, 6, 1, 4, 1, 9442, 1, 3, 1, 1, 2, 0 };
    static oid      dot11CurrentTxRate_oid[] =
        { 1, 3, 6, 1, 4, 1, 9442, 1, 3, 3, 2, 2, 0 };
    static oid      dot11TurboModeEnabled_oid[] =
        { 1, 3, 6, 1, 4, 1, 9442, 1, 3, 3, 2, 3, 0 };
    static oid      dot11CountryString_oid[] =
        { 1, 3, 6, 1, 4, 1, 9442, 1, 3, 1, 1, 3, 0 };
    static oid      dot11MultiDomainCapabilityImplemented_oid[] =
        { 1, 3, 6, 1, 4, 1, 9442, 1, 3, 1, 1, 1, 0 };

    DEBUGMSGTL(("atherosAPdot11_scalar", "Initializing\n"));

    netsnmp_register_instance(netsnmp_create_handler_registration
                              ("dot11MultiDomainCapabilityEnabled",
                               do_dot11MultiDomainCapabilityEnabled,
                               dot11MultiDomainCapabilityEnabled_oid,
                               OID_LENGTH
                               (dot11MultiDomainCapabilityEnabled_oid),
                               HANDLER_CAN_RWRITE));
    netsnmp_register_instance(netsnmp_create_handler_registration
                              ("dot11CurrentTxRate", do_dot11CurrentTxRate,
                               dot11CurrentTxRate_oid,
                               OID_LENGTH(dot11CurrentTxRate_oid),
                               HANDLER_CAN_RWRITE));
    netsnmp_register_read_only_instance(netsnmp_create_handler_registration
                                        ("dot11TurboModeEnabled",
                                         get_dot11TurboModeEnabled,
                                         dot11TurboModeEnabled_oid,
                                         OID_LENGTH
                                         (dot11TurboModeEnabled_oid),
                                         HANDLER_CAN_RONLY));
    netsnmp_register_read_only_instance(netsnmp_create_handler_registration
                                        ("dot11CountryString",
                                         get_dot11CountryString,
                                         dot11CountryString_oid,
                                         OID_LENGTH
                                         (dot11CountryString_oid),
                                         HANDLER_CAN_RONLY));
    netsnmp_register_read_only_instance(netsnmp_create_handler_registration
                                        ("dot11MultiDomainCapabilityImplemented",
                                         get_dot11MultiDomainCapabilityImplemented,
                                         dot11MultiDomainCapabilityImplemented_oid,
                                         OID_LENGTH
                                         (dot11MultiDomainCapabilityImplemented_oid),
                                         HANDLER_CAN_RONLY));
}

int
do_dot11MultiDomainCapabilityEnabled(netsnmp_mib_handler *handler,
                                     netsnmp_handler_registration *reginfo,
                                     netsnmp_agent_request_info *reqinfo,
                                     netsnmp_request_info *requests)
{
  	static MYEnumVal enabled=1;
	netsnmp_variable_list *var;
	var=requests->requestvb;
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (u_char *)&enabled,sizeof(MYEnumVal));
        break;

    case MODE_SET_RESERVE1:
        if (var->type!=ASN_INTEGER) 
        	netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGTYPE);
	else if(var->val_len!=sizeof(MYEnumVal))
		netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGLENGTH);
	else if(*var->val.integer!=1 && *var->val.integer!=2)
		netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGVALUE);
	else
		;
        break;

    case MODE_SET_RESERVE2:
        if ( backup(&enabled,sizeof(MYEnumVal))) {
            netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_GENERR);
        }
        break;

    case MODE_SET_FREE:
        clear();
        break;

    case MODE_SET_ACTION:
        enabled=*var->val.integer;
        break;

    case MODE_SET_COMMIT:
		clear();
        break;

    case MODE_SET_UNDO:
        if ( restore(&enabled,sizeof(MYEnumVal)))
            netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
        
        break;
    default:
        MYMARK("unknown  mode");
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
do_dot11CurrentTxRate(netsnmp_mib_handler *handler,
                      netsnmp_handler_registration *reginfo,
                      netsnmp_agent_request_info *reqinfo,
                      netsnmp_request_info *requests)
{
	static MYINTEGER rate=6;
	netsnmp_variable_list *var;
	var=requests->requestvb;

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (u_char *)&rate,sizeof(MYINTEGER));
        break;

    case MODE_SET_RESERVE1:
         if (var->type!=ASN_INTEGER) 
        	netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGTYPE);
	else if(var->val_len!=sizeof(MYINTEGER))
		netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGLENGTH);
	else if(*var->val.integer<6 || *var->val.integer>54)
		netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_WRONGVALUE);
	else
		;
        break;

    case MODE_SET_RESERVE2:
         if ( backup(&rate,sizeof(MYINTEGER)) ) 
            netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_GENERR);
         break;
    case MODE_SET_FREE:
        clear();
        break;

    case MODE_SET_ACTION:
        rate=*var->val.integer;
        break;

    case MODE_SET_COMMIT:
        clear();
        break;

    case MODE_SET_UNDO:
        
        if ( restore(&rate,sizeof(MYINTEGER))) 
            netsnmp_set_request_error(reqinfo, requests,
                                      SNMP_ERR_UNDOFAILED);
        break;

    default:
        MYMARK("unknown  mode");
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
get_dot11TurboModeEnabled(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info *reqinfo,
                          netsnmp_request_info *requests)
{
	MYEnumVal enabled=1;
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&enabled,sizeof(MYEnumVal));
        break;
    default:
        MYMARK("unknow mode");
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
get_dot11CountryString(netsnmp_mib_handler *handler,
                       netsnmp_handler_registration *reginfo,
                       netsnmp_agent_request_info *reqinfo,
                       netsnmp_request_info *requests)
{
	char* str="123";
    switch (reqinfo->mode) {
    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                 (u_char *)str,3);
        break;
    default:
        MYMARK("unknow mode");
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
get_dot11MultiDomainCapabilityImplemented(netsnmp_mib_handler *handler,
                                          netsnmp_handler_registration
                                          *reginfo,
                                          netsnmp_agent_request_info
                                          *reqinfo,
                                          netsnmp_request_info *requests)
{
    MYEnumVal tmp=1;
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&tmp,sizeof(MYEnumVal));
        break;
    default:
        MYMARK("Unknow mode");
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
