/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef ATHEROSAPDOT11_SCALAR_H
#define ATHEROSAPDOT11_SCALAR_H

/*
 * function declarations 
 */
void            init_atherosAPdot11_scalar(void);
Netsnmp_Node_Handler do_dot11MultiDomainCapabilityEnabled;
Netsnmp_Node_Handler do_dot11CurrentTxRate;
Netsnmp_Node_Handler get_dot11TurboModeEnabled;
Netsnmp_Node_Handler get_dot11CountryString;
Netsnmp_Node_Handler get_dot11MultiDomainCapabilityImplemented;
#ifndef MY_DEBUG
#define MY_DEBUG
#define MYSTART(s)      printf("\n***** start  ***** %s %s %d\n",s,__FILE__,__LINE__);
#define MYEND(s)        printf("\n*****  end   ***** %s %s %d\n",s,__FILE__,__LINE__);
#define MYMARK(s)       printf("\n***** mark   ***** %s %s %d\n",s,__FILE__,__LINE__);
#define MYIN()          printf("\n***** in     ***** %s %s %d\n",__FUNCTION__,__FILE__,__LINE__);
#define MYOUT()          printf("\n***** out   ***** %s %s %d\n",__FUNCTION__,__FILE__,__LINE__);
#endif

#endif                          /* ATHEROSAPDOT11_SCALAR_H */
